sudo: required

services:
  - docker

language: java

jdk:
  - oraclejdk8
  
after_success:
  - >
  [ "$TRAVIS_BRANCH" == "master" ]
  && curl -X POST -H "Content-Type: application/json"
  --data '{"docker_tag_name": "latest"}'
  https://registry.hub.docker.com/u/totowen/templete/trigger/$DOCKER_HUB_TOKEN/

  