#开发环境
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/test
  username: root
  password: Jovaunn1
  driver-class-name: com.mysql.jdbc.Driver

#spring:
# datasource:
#  url: jdbc:oracle:thin:@192.168.1.117:1521:orcl
#  username: vortex
#  password: vortex2016
#  driver-class-oracle: jdbc.driver.OracleDriver

# 服务端口
server:
 port: 8010